Implemented GameCard component, search by name and navigation links to product categories
thatverygeorge/itechart-lab pull request #4
Opened 2021-09-21 12:10 UTC by thatverygeorge

2021-09-21 12:48 UTC, StasKhitrich requested changes

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/aboutScreen/aboutScreen.module.scss
> +  background: -webkit-linear-gradient(-45deg, $dakr-cyan 0%, $dark-violet 100%);
Это префикс для браузеров на движке Chrome, а на общее свойство для создания градиента.
Там внизу есть примеры. У тебя в проекте авто префиксер включен в postcss, он сам добавит эти префиксы. Тебе надо юзать linear-gradient.
http://htmlbook.ru/css/-webkit-linear-gradient

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/buttonAddToCart/buttonAddToCart.module.scss
> +  margin-top: auto;
Общее напутствие: margin-top старайся не использовать без веской причины, есть схлопывание, если где-то используешь, лучше подумать о рефакторинге. Старайся следовать потоку слева-направо, сверху-вниз
https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/buttonAddToCart/buttonAddToCart.module.scss
> +.addToCart:hover,
Ты же SCSS используешь, можешь эффекты внутри классов писать через амперсант (&:hover)

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/gameCard/gameCard.tsx
> +    image.src = "https://via.placeholder.com/250x340";
Вынести placeholder в константу вне компонента

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/homeScreen/homeScreen.tsx
> +const getNewGames = (onSuccess) => {
Архитектурный момент. Хранить методы с запросами прямо в компонентах - не очень хорошая практика, подумай над созданием некого метода для запросов, который будет уметь обрабатывать ответы сервера, что-то делать с ошибками и так далее. В дальнейшем, с Redux, у тебя будет возможность отправлять туда ошибку и выводить где-то в приложении без дополнительных манипуляций в каждом компоненте.

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/homeScreen/homeScreen.tsx
> +  fetch("/api/products/getTopProducts", {
Следует задуматься над созданием единого хранилища API URLS, чтобы переопределять можно было в одном месте и это распространялось на весь проект.

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/homeScreen/homeScreen.tsx
> +    method: "GET",
Метод GET у fetch по умолчанию - это лишнее

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/homeScreen/homeScreen.tsx
> +        {newGames.length > 0 ? (
Проверка > 0 не имеет смысла, если там больше нуля, то это true автоматически

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/loadingSpinner/loadingSpinner.tsx
> +const LoadingSpinner = ({ title }: ILoadingSpinnerProps): ReactElement => (
Компонент LoadingSpinner, но кажется сам компонент выводит лишь текст о загрузке, так?

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/navigation/navigation.tsx
> +            isActive={() => getIsLinkActive(["/products", ...Object.values(ProductsRoutes).map((route) => route.path)])}
Стоит подготовить данные заранее, это не работа шаблона заниматься сложной логикой. Можно создать отдельный метод для этого.

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/platformsList/platformsList.module.scss
> +  background-image: url("../../assets/images/icons/icon-pc.svg");
У тебя есть точно такие же классы для link, возможно стоит вынести дублирование в отдельный общий файл, например icons.scss

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/platformsList/platformsList.tsx
> +        <p className="visually-hidden">{platform}</p>
Для малого количества текста и внутри li, семантически лучше использовать инлайновый span

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/gameCard/gameCard.tsx
> +    <li className={styles.card}>
Нужен ли тут li, а в обёртке ul?
Прежде всего, это не подходит к названию gamesCard, ведь это не gamesItem.
Также, это очень ограничивает места в которых можно использовать компонент, ведь необходим ul, ol в обёртке.
Ну и также в li, по семантике, не стоит располагать блочные элементы типа div, p

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/productsScreen/productsScreen.tsx
> +        <GamesList title={GAMES_LIST_TITLE} games={GAMES.filter(filterGameByPlatform)} />
Если нет platform в урле, то можно сразу вставлять GAMES, не обязательно запускать filter и можно убрать лишнюю проверку в функции фильтрации
!platform ? GAMES : GAMES.filter()

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/search/search.tsx
> +    const textToSearch = inputRef.current.value.trim().toLowerCase();
По идее, сюда прокидывается event и тебе нет необходимости использовать inputRef.current, проверь пожалуйста

2021-09-21 12:48 UTC, StasKhitrich commented on src/components/userRating/userRating.tsx
> +    {new Array(5).fill(null).map((_, index) => {
Упрости шаблон, вынеси часть или всю логику из шаблона, не стоит всё подряд писать прям в HTML

2021-09-21 12:48 UTC, StasKhitrich commented on src/mocks/games.tsx
> +    platforms: ["PC", "PlayStation", "Xbox"],
Что будет, если ошибиться при вводе платформ тут?
Может стоит в константе хранить платформы?

2021-09-21 12:48 UTC, StasKhitrich commented on src/state.tsx
> +    case "changeIsLoading":
Типы экшенов лучше хранить в отдельном файле или просто в виде констант

2021-09-21 12:48 UTC, StasKhitrich commented on src/utils/debounce.ts
> +const TIME_OUT = 300;
Этой константе тут не место, можешь сделать её либо где-то в общем конфиге приложения, либо передавай в метод debounce как второй, не обязательный, параметр. 
debounce(callback, delay = 300)

2021-09-21 12:48 UTC, StasKhitrich commented on src/utils/debounce.ts
> +const debounce = (callback: (...args) => unknown): (() => void) => {
Можешь создать отдельный тип для debounce прямо над ней для улучшения читабельности
(callback: () => void, delay: number) => (() => void)

2021-09-22 12:09 UTC, SnovikWeb approved these changes

2021-09-22 12:10 UTC, merged